### 라이브러리 설정

In [32]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### 데이터 불러오기

In [33]:
data = pd.read_csv("/home/jun/my_project/data_analistic/speed_dating.csv")
data.head()

,Unnamed: 0,has_null,gender,age,age_o,race,race_o,importance_same_race,importance_same_religion,pref_o_attractive,pref_o_sincere,pref_o_intelligence,pref_o_funny,pref_o_ambitious,pref_o_shared_interests,attractive_o,sincere_o,intelligence_o,funny_o,ambitous_o,shared_interests_o,attractive_important,sincere_important,intellicence_important,funny_important,ambtition_important,shared_interests_important,attractive_partner,sincere_partner,intelligence_partner,funny_partner,ambition_partner,shared_interests_partner,interests_correlate,expected_happy_with_sd_people,expected_num_interested_in_me,like,guess_prob_liked,met,match
0,0,0,female,21.0,27.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,35.0,20.0,20.0,20.0,0.0,5.0,6.0,8.0,8.0,8.0,8.0,6.0,15.0,20.0,20.0,15.0,15.0,15.0,6.0,9.0,7.0,7.0,6.0,5.0,0.14,3.0,2.0,7.0,6.0,0.0,0
1,1,0,female,21.0,22.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,60.0,0.0,0.0,40.0,0.0,0.0,7.0,8.0,10.0,7.0,7.0,5.0,15.0,20.0,20.0,15.0,15.0,15.0,7.0,8.0,7.0,8.0,5.0,6.0,0.54,3.0,2.0,7.0,5.0,1.0,0
2,2,1,female,21.0,22.0,Asian/PacificIslander/Asian-American,Asian/PacificIslander/Asian-American,2.0,4.0,19.0,18.0,19.0,18.0,14.0,12.0,10.0,10.0,10.0,10.0,10.0,10.0,15.0,20.0,20.0,15.0,15.0,15.0,5.0,8.0,9.0,8.0,5.0,7.0,0.16,3.0,2.0,7.0,NaN,1.0,1
3,3,0,female,21.0,23.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,30.0,5.0,15.0,40.0,5.0,5.0,7.0,8.0,9.0,8.0,9.0,8.0,15.0,20.0,20.0,15.0,15.0,15.0,7.0,6.0,8.0,7.0,6.0,8.0,0.61,3.0,2.0,7.0,6.0,0.0,1
4,4,0,female,21.0,24.0,Asian/PacificIslander/Asian-American,Latino/HispanicAmerican,2.0,4.0,30.0,10.0,20.0,10.0,10.0,20.0,8.0,7.0,9.0,6.0,9.0,7.0,15.0,20.0,20.0,15.0,15.0,15.0,5.0,6.0,7.0,7.0,6.0,6.0,0.21,3.0,2.0,6.0,6.0,0.0,1

## 데이터 확인하기

In [34]:
data = pd.read_csv("/home/jun/my_project/data_analistic/speed_dating.csv",index_col=0)
    # index_col : 설정해주지 않으면 기본 숫자 인덱스열을 생성함
    # 근데 이 파일에선 이미 숫자 인덱스열이 설정되어있으므로, 중복되므로 빼줌 = 다른 열을 인덱스열로 설정!
data.head()

,has_null,gender,age,age_o,race,race_o,importance_same_race,importance_same_religion,pref_o_attractive,pref_o_sincere,pref_o_intelligence,pref_o_funny,pref_o_ambitious,pref_o_shared_interests,attractive_o,sincere_o,intelligence_o,funny_o,ambitous_o,shared_interests_o,attractive_important,sincere_important,intellicence_important,funny_important,ambtition_important,shared_interests_important,attractive_partner,sincere_partner,intelligence_partner,funny_partner,ambition_partner,shared_interests_partner,interests_correlate,expected_happy_with_sd_people,expected_num_interested_in_me,like,guess_prob_liked,met,match
0,0,female,21.0,27.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,35.0,20.0,20.0,20.0,0.0,5.0,6.0,8.0,8.0,8.0,8.0,6.0,15.0,20.0,20.0,15.0,15.0,15.0,6.0,9.0,7.0,7.0,6.0,5.0,0.14,3.0,2.0,7.0,6.0,0.0,0
1,0,female,21.0,22.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,60.0,0.0,0.0,40.0,0.0,0.0,7.0,8.0,10.0,7.0,7.0,5.0,15.0,20.0,20.0,15.0,15.0,15.0,7.0,8.0,7.0,8.0,5.0,6.0,0.54,3.0,2.0,7.0,5.0,1.0,0
2,1,female,21.0,22.0,Asian/PacificIslander/Asian-American,Asian/PacificIslander/Asian-American,2.0,4.0,19.0,18.0,19.0,18.0,14.0,12.0,10.0,10.0,10.0,10.0,10.0,10.0,15.0,20.0,20.0,15.0,15.0,15.0,5.0,8.0,9.0,8.0,5.0,7.0,0.16,3.0,2.0,7.0,NaN,1.0,1
3,0,female,21.0,23.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,30.0,5.0,15.0,40.0,5.0,5.0,7.0,8.0,9.0,8.0,9.0,8.0,15.0,20.0,20.0,15.0,15.0,15.0,7.0,6.0,8.0,7.0,6.0,8.0,0.61,3.0,2.0,7.0,6.0,0.0,1
4,0,female,21.0,24.0,Asian/PacificIslander/Asian-American,Latino/HispanicAmerican,2.0,4.0,30.0,10.0,20.0,10.0,10.0,20.0,8.0,7.0,9.0,6.0,9.0,7.0,15.0,20.0,20.0,15.0,15.0,15.0,5.0,6.0,7.0,7.0,6.0,6.0,0.21,3.0,2.0,6.0,6.0,0.0,1

In [35]:
# 열(=변수)의 개수가 39개나 되어서 기본 화면에 다 출력하지 못함 -> ...으로 표시
# 설정 바꿀 수 있음
pd.options.display.max_columns = 40
data.head()

,has_null,gender,age,age_o,race,race_o,importance_same_race,importance_same_religion,pref_o_attractive,pref_o_sincere,pref_o_intelligence,pref_o_funny,pref_o_ambitious,pref_o_shared_interests,attractive_o,sincere_o,intelligence_o,funny_o,ambitous_o,shared_interests_o,attractive_important,sincere_important,intellicence_important,funny_important,ambtition_important,shared_interests_important,attractive_partner,sincere_partner,intelligence_partner,funny_partner,ambition_partner,shared_interests_partner,interests_correlate,expected_happy_with_sd_people,expected_num_interested_in_me,like,guess_prob_liked,met,match
0,0,female,21.0,27.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,35.0,20.0,20.0,20.0,0.0,5.0,6.0,8.0,8.0,8.0,8.0,6.0,15.0,20.0,20.0,15.0,15.0,15.0,6.0,9.0,7.0,7.0,6.0,5.0,0.14,3.0,2.0,7.0,6.0,0.0,0
1,0,female,21.0,22.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,60.0,0.0,0.0,40.0,0.0,0.0,7.0,8.0,10.0,7.0,7.0,5.0,15.0,20.0,20.0,15.0,15.0,15.0,7.0,8.0,7.0,8.0,5.0,6.0,0.54,3.0,2.0,7.0,5.0,1.0,0
2,1,female,21.0,22.0,Asian/PacificIslander/Asian-American,Asian/PacificIslander/Asian-American,2.0,4.0,19.0,18.0,19.0,18.0,14.0,12.0,10.0,10.0,10.0,10.0,10.0,10.0,15.0,20.0,20.0,15.0,15.0,15.0,5.0,8.0,9.0,8.0,5.0,7.0,0.16,3.0,2.0,7.0,NaN,1.0,1
3,0,female,21.0,23.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,30.0,5.0,15.0,40.0,5.0,5.0,7.0,8.0,9.0,8.0,9.0,8.0,15.0,20.0,20.0,15.0,15.0,15.0,7.0,6.0,8.0,7.0,6.0,8.0,0.61,3.0,2.0,7.0,6.0,0.0,1
4,0,female,21.0,24.0,Asian/PacificIslander/Asian-American,Latino/HispanicAmerican,2.0,4.0,30.0,10.0,20.0,10.0,10.0,20.0,8.0,7.0,9.0,6.0,9.0,7.0,15.0,20.0,20.0,15.0,15.0,15.0,5.0,6.0,7.0,7.0,6.0,6.0,0.21,3.0,2.0,6.0,6.0,0.0,1

In [36]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8378 entries, 0 to 8377
Data columns (total 39 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   has_null                       8378 non-null   int64
 1   gender                         8378 non-null   object
 2   age                            8283 non-null   float64
 3   age_o                          8274 non-null   float64
 4   race                           8315 non-null   object
 5   race_o                         8305 non-null   object
 6   importance_same_race           8299 non-null   float64
 7   importance_same_religion       8299 non-null   float64
 8   pref_o_attractive              8289 non-null   float64
 9   pref_o_sincere                 8289 non-null   float64
 10  pref_o_intelligence            8289 non-null   float64
 11  pref_o_funny                   8280 non-null   float64
 12  pref_o_ambitious               8271 non-null   float64
 13  pref_o_shared_interests        8249 non-null   float64
 14  attractive_o                   8166 non-null   float64
 15  sincere_o                      8091 non-null   float64
 16  intelligence_o                 8072 non-null   float64
 17  funny_o                        8018 non-null   float64
 18  ambitous_o                     7656 non-null   float64
 19  shared_interests_o             7302 non-null   float64
 20  attractive_important           8299 non-null   float64
 21  sincere_important              8299 non-null   float64
 22  intellicence_important         8299 non-null   float64
 23  funny_important                8289 non-null   float64
 24  ambtition_important            8279 non-null   float64
 25  shared_interests_important     8257 non-null   float64
 26  attractive_partner             8176 non-null   float64
 27  sincere_partner                8101 non-null   float64
 28  intelligence_partner           8082 non-null   float64
 29  funny_partner                  8028 non-null   float64
 30  ambition_partner               7666 non-null   float64
 31  shared_interests_partner       7311 non-null   float64
 32  interests_correlate            8220 non-null   float64
 33  expected_happy_with_sd_people  8277 non-null   float64
 34  expected_num_interested_in_me  1800 non-null   float64
 35  like                           8138 non-null   float64
 36  guess_prob_liked               8069 non-null   float64
 37  met                            8003 non-null   float64
 38  match                          8378 non-null   int64
dtypes: float64(34), int64(2), object(3)
memory usage: 2.6+ MB

1. 8378개의 관측치 = 행
2. 39개의 변수 = 열
3. match : 종속변수 <- 나머지 : 독립변수

In [37]:
round(data.describe(),2)

,has_null,age,age_o,importance_same_race,importance_same_religion,pref_o_attractive,pref_o_sincere,pref_o_intelligence,pref_o_funny,pref_o_ambitious,pref_o_shared_interests,attractive_o,sincere_o,intelligence_o,funny_o,ambitous_o,shared_interests_o,attractive_important,sincere_important,intellicence_important,funny_important,ambtition_important,shared_interests_important,attractive_partner,sincere_partner,intelligence_partner,funny_partner,ambition_partner,shared_interests_partner,interests_correlate,expected_happy_with_sd_people,expected_num_interested_in_me,like,guess_prob_liked,met,match
count,8378.00,8283.00,8274.00,8299.00,8299.00,8289.00,8289.00,8289.00,8280.00,8271.00,8249.00,8166.00,8091.00,8072.00,8018.00,7656.00,7302.00,8299.00,8299.00,8299.00,8289.00,8279.00,8257.00,8176.00,8101.00,8082.00,8028.00,7666.00,7311.00,8220.00,8277.00,1800.00,8138.00,8069.00,8003.00,8378.00
mean,0.87,26.36,26.36,3.78,3.65,22.50,17.40,20.27,17.46,10.69,11.85,6.19,7.18,7.37,6.40,6.78,5.47,22.51,17.40,20.27,17.46,10.68,11.85,6.19,7.18,7.37,6.40,6.78,5.47,0.20,5.53,5.57,6.13,5.21,0.05,0.16
std,0.33,3.57,3.56,2.85,2.81,12.57,7.04,6.78,6.09,6.13,6.36,1.95,1.74,1.55,1.95,1.79,2.16,12.59,7.05,6.78,6.09,6.12,6.36,1.95,1.74,1.55,1.95,1.79,2.16,0.30,1.73,4.76,1.84,2.13,0.28,0.37
min,0.00,18.00,18.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-0.83,1.00,0.00,0.00,0.00,0.00,0.00
25%,1.00,24.00,24.00,1.00,1.00,15.00,15.00,17.39,15.00,5.00,9.52,5.00,6.00,6.00,5.00,6.00,4.00,15.00,15.00,17.39,15.00,5.00,9.52,5.00,6.00,6.00,5.00,6.00,4.00,-0.02,5.00,2.00,5.00,4.00,0.00,0.00
50%,1.00,26.00,26.00,3.00,3.00,20.00,18.37,20.00,18.00,10.00,10.64,6.00,7.00,7.00,7.00,7.00,6.00,20.00,18.18,20.00,18.00,10.00,10.64,6.00,7.00,7.00,7.00,7.00,6.00,0.21,6.00,4.00,6.00,5.00,0.00,0.00
75%,1.00,28.00,28.00,6.00,6.00,25.00,20.00,23.81,20.00,15.00,16.00,8.00,8.00,8.00,8.00,8.00,7.00,25.00,20.00,23.81,20.00,15.00,16.00,8.00,8.00,8.00,8.00,8.00,7.00,0.43,7.00,8.00,7.00,7.00,0.00,0.00
max,1.00,55.00,55.00,10.00,10.00,100.00,60.00,50.00,50.00,53.00,30.00,10.50,10.00,10.00,11.00,10.00,10.00,100.00,60.00,50.00,50.00,53.00,30.00,10.00,10.00,10.00,10.00,10.00,10.00,0.91,10.00,20.00,10.00,10.00,8.00,1.00

## 전처리

### 결측치

In [40]:
# 결측치 비율 확인
data.isna().mean()

has_null                         0.0
gender                           0.0
age                              0.0
age_o                            0.0
race                             0.0
race_o                           0.0
importance_same_race             0.0
importance_same_religion         0.0
pref_o_attractive                0.0
pref_o_sincere                   0.0
pref_o_intelligence              0.0
pref_o_funny                     0.0
pref_o_ambitious                 0.0
pref_o_shared_interests          0.0
attractive_o                     0.0
sincere_o                        0.0
intelligence_o                   0.0
funny_o                          0.0
ambitous_o                       0.0
shared_interests_o               0.0
attractive_important             0.0
sincere_important                0.0
intellicence_important           0.0
funny_important                  0.0
ambtition_important              0.0
shared_interests_important       0.0
attractive_partner               0.0
sincere_partner                  0.0
intelligence_partner             0.0
funny_partner                    0.0
ambition_partner                 0.0
shared_interests_partner         0.0
interests_correlate              0.0
expected_happy_with_sd_people    0.0
expected_num_interested_in_me    0.0
like                             0.0
guess_prob_liked                 0.0
met                              0.0
match                            0.0
dtype: float64

결측치 채우기
- 데이터에 등장하지 않을 법한 임의의 수를 넣음
- 선형모델에선 아웃라이어로 취급되지만
- 트리모델에선 결측치라는 사실 자체로서 유의미한 노드가 생길 것

In [41]:
data = data.dropna(subset=['pref_o_attractive',
'pref_o_sincere',                  
'pref_o_intelligence',            
'pref_o_funny',                     
'pref_o_ambitious',             
'pref_o_shared_interests',          
'attractive_o',                     
'sincere_o',                        
'intelligence_o',                   
'funny_o',                          
'ambitous_o',                
'shared_interests_o'])
    # 중요도와 관련된 부분은 결측치 제거함

data = data.fillna(-99)
data.info() # 결측치 다 사라짐
data.head(10)

<class 'pandas.core.frame.DataFrame'>
Index: 6924 entries, 0 to 8377
Data columns (total 39 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   has_null                       6924 non-null   int64
 1   gender                         6924 non-null   object
 2   age                            6924 non-null   float64
 3   age_o                          6924 non-null   float64
 4   race                           6924 non-null   object
 5   race_o                         6924 non-null   object
 6   importance_same_race           6924 non-null   float64
 7   importance_same_religion       6924 non-null   float64
 8   pref_o_attractive              6924 non-null   float64
 9   pref_o_sincere                 6924 non-null   float64
 10  pref_o_intelligence            6924 non-null   float64
 11  pref_o_funny                   6924 non-null   float64
 12  pref_o_ambitious               6924 non-null   float64
 13  pref_o_shared_interests        6924 non-null   float64
 14  attractive_o                   6924 non-null   float64
 15  sincere_o                      6924 non-null   float64
 16  intelligence_o                 6924 non-null   float64
 17  funny_o                        6924 non-null   float64
 18  ambitous_o                     6924 non-null   float64
 19  shared_interests_o             6924 non-null   float64
 20  attractive_important           6924 non-null   float64
 21  sincere_important              6924 non-null   float64
 22  intellicence_important         6924 non-null   float64
 23  funny_important                6924 non-null   float64
 24  ambtition_important            6924 non-null   float64
 25  shared_interests_important     6924 non-null   float64
 26  attractive_partner             6924 non-null   float64
 27  sincere_partner                6924 non-null   float64
 28  intelligence_partner           6924 non-null   float64
 29  funny_partner                  6924 non-null   float64
 30  ambition_partner               6924 non-null   float64
 31  shared_interests_partner       6924 non-null   float64
 32  interests_correlate            6924 non-null   float64
 33  expected_happy_with_sd_people  6924 non-null   float64
 34  expected_num_interested_in_me  6924 non-null   float64
 35  like                           6924 non-null   float64
 36  guess_prob_liked               6924 non-null   float64
 37  met                            6924 non-null   float64
 38  match                          6924 non-null   int64
dtypes: float64(34), int64(2), object(3)
memory usage: 2.1+ MB

,has_null,gender,age,age_o,race,race_o,importance_same_race,importance_same_religion,pref_o_attractive,pref_o_sincere,pref_o_intelligence,pref_o_funny,pref_o_ambitious,pref_o_shared_interests,attractive_o,sincere_o,intelligence_o,funny_o,ambitous_o,shared_interests_o,attractive_important,sincere_important,intellicence_important,funny_important,ambtition_important,shared_interests_important,attractive_partner,sincere_partner,intelligence_partner,funny_partner,ambition_partner,shared_interests_partner,interests_correlate,expected_happy_with_sd_people,expected_num_interested_in_me,like,guess_prob_liked,met,match
0,0,female,21.0,27.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,35.00,20.00,20.00,20.00,0.00,5.00,6.0,8.0,8.0,8.0,8.0,6.0,15.0,20.0,20.0,15.0,15.0,15.0,6.0,9.0,7.0,7.0,6.0,5.0,0.14,3.0,2.0,7.0,6.0,0.0,0
1,0,female,21.0,22.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,60.00,0.00,0.00,40.00,0.00,0.00,7.0,8.0,10.0,7.0,7.0,5.0,15.0,20.0,20.0,15.0,15.0,15.0,7.0,8.0,7.0,8.0,5.0,6.0,0.54,3.0,2.0,7.0,5.0,1.0,0
2,1,female,21.0,22.0,Asian/PacificIslander/Asian-American,Asian/PacificIslander/Asian-American,2.0,4.0,19.00,18.00,19.00,18.00,14.00,12.00,10.0,10.0,10.0,10.0,10.0,10.0,15.0,20.0,20.0,15.0,15.0,15.0,5.0,8.0,9.0,8.0,5.0,7.0,0.16,3.0,2.0,7.0,-99.0,1.0,1
3,0,female,21.0,23.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,30.00,5.00,15.00,40.00,5.00,5.00,7.0,8.0,9.0,8.0,9.0,8.0,15.0,20.0,20.0,15.0,15.0,15.0,7.0,6.0,8.0,7.0,6.0,8.0,0.61,3.0,2.0,7.0,6.0,0.0,1
4,0,female,21.0,24.0,Asian/PacificIslander/Asian-American,Latino/HispanicAmerican,2.0,4.0,30.00,10.00,20.00,10.00,10.00,20.00,8.0,7.0,9.0,6.0,9.0,7.0,15.0,20.0,20.0,15.0,15.0,15.0,5.0,6.0,7.0,7.0,6.0,6.0,0.21,3.0,2.0,6.0,6.0,0.0,1
5,0,female,21.0,25.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,50.00,0.00,30.00,10.00,0.00,10.00,7.0,7.0,8.0,8.0,7.0,7.0,15.0,20.0,20.0,15.0,15.0,15.0,4.0,9.0,7.0,4.0,6.0,4.0,0.25,3.0,2.0,6.0,5.0,0.0,0
6,0,female,21.0,30.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,35.00,15.00,25.00,10.00,5.00,10.00,3.0,6.0,7.0,5.0,8.0,7.0,15.0,20.0,20.0,15.0,15.0,15.0,7.0,6.0,7.0,4.0,6.0,7.0,0.34,3.0,2.0,6.0,5.0,0.0,0
7,1,female,21.0,27.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,33.33,11.11,11.11,11.11,11.11,22.22,6.0,7.0,5.0,6.0,8.0,6.0,15.0,20.0,20.0,15.0,15.0,15.0,4.0,9.0,7.0,6.0,5.0,6.0,0.50,3.0,2.0,6.0,7.0,-99.0,0
8,0,female,21.0,28.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,50.00,0.00,25.00,10.00,0.00,15.00,7.0,7.0,8.0,8.0,8.0,9.0,15.0,20.0,20.0,15.0,15.0,15.0,7.0,6.0,8.0,9.0,8.0,8.0,0.28,3.0,2.0,7.0,7.0,0.0,1
9,0,female,21.0,24.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,100.00,0.00,0.00,0.00,0.00,0.00,6.0,6.0,6.0,6.0,6.0,6.0,15.0,20.0,20.0,15.0,15.0,15.0,5.0,6.0,6.0,8.0,10.0,8.0,-0.36,3.0,2.0,6.0,6.0,0.0,0

### 피쳐 엔지니어링

#### 나이

In [42]:
def age_gap(x):
    if x['age'] == -99:
        return -99
    elif x['age_o'] == -99:
        return -99
    elif x['gender'] == 'female':
        return x['age_o'] - x['age']
    else:
        return x['age'] - x['age_o']

In [43]:
data['age_gap'] = data.apply(age_gap, axis=1)

In [44]:
data['age_gap_abs'] = abs(data['age_gap'])
data['age_gap_abs'].describe()

count    6924.000000
mean        4.843588
std        11.211308
min         0.000000
25%         1.000000
50%         3.000000
75%         5.000000
max        99.000000
Name: age_gap_abs, dtype: float64

#### 인종

In [45]:
def same_race(x):
    if x['race'] == -99:
        return -99
    elif x['race_o'] == -99:
        return -99
    elif x['race'] == x['race_o']:
        return 1
    else:
        return -1

In [46]:
data['same_race'] = data.apply(same_race, axis=1)
data.head()

,has_null,gender,age,age_o,race,race_o,importance_same_race,importance_same_religion,pref_o_attractive,pref_o_sincere,pref_o_intelligence,pref_o_funny,pref_o_ambitious,pref_o_shared_interests,attractive_o,sincere_o,intelligence_o,funny_o,ambitous_o,shared_interests_o,...,intellicence_important,funny_important,ambtition_important,shared_interests_important,attractive_partner,sincere_partner,intelligence_partner,funny_partner,ambition_partner,shared_interests_partner,interests_correlate,expected_happy_with_sd_people,expected_num_interested_in_me,like,guess_prob_liked,met,match,age_gap,age_gap_abs,same_race
0,0,female,21.0,27.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,35.0,20.0,20.0,20.0,0.0,5.0,6.0,8.0,8.0,8.0,8.0,6.0,...,20.0,15.0,15.0,15.0,6.0,9.0,7.0,7.0,6.0,5.0,0.14,3.0,2.0,7.0,6.0,0.0,0,6.0,6.0,-1
1,0,female,21.0,22.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,60.0,0.0,0.0,40.0,0.0,0.0,7.0,8.0,10.0,7.0,7.0,5.0,...,20.0,15.0,15.0,15.0,7.0,8.0,7.0,8.0,5.0,6.0,0.54,3.0,2.0,7.0,5.0,1.0,0,1.0,1.0,-1
2,1,female,21.0,22.0,Asian/PacificIslander/Asian-American,Asian/PacificIslander/Asian-American,2.0,4.0,19.0,18.0,19.0,18.0,14.0,12.0,10.0,10.0,10.0,10.0,10.0,10.0,...,20.0,15.0,15.0,15.0,5.0,8.0,9.0,8.0,5.0,7.0,0.16,3.0,2.0,7.0,-99.0,1.0,1,1.0,1.0,1
3,0,female,21.0,23.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,30.0,5.0,15.0,40.0,5.0,5.0,7.0,8.0,9.0,8.0,9.0,8.0,...,20.0,15.0,15.0,15.0,7.0,6.0,8.0,7.0,6.0,8.0,0.61,3.0,2.0,7.0,6.0,0.0,1,2.0,2.0,-1
4,0,female,21.0,24.0,Asian/PacificIslander/Asian-American,Latino/HispanicAmerican,2.0,4.0,30.0,10.0,20.0,10.0,10.0,20.0,8.0,7.0,9.0,6.0,9.0,7.0,...,20.0,15.0,15.0,15.0,5.0,6.0,7.0,7.0,6.0,6.0,0.21,3.0,2.0,6.0,6.0,0.0,1,3.0,3.0,-1

In [47]:
def smae_race_point(x):
    if x['same_race'] == -99:
        return -99
    else:
        return x['same_race'] * x['importance_same_race']

In [48]:
data['same_race_point'] = data.apply(smae_race_point, axis=1)
data.head()

,has_null,gender,age,age_o,race,race_o,importance_same_race,importance_same_religion,pref_o_attractive,pref_o_sincere,pref_o_intelligence,pref_o_funny,pref_o_ambitious,pref_o_shared_interests,attractive_o,sincere_o,intelligence_o,funny_o,ambitous_o,shared_interests_o,...,funny_important,ambtition_important,shared_interests_important,attractive_partner,sincere_partner,intelligence_partner,funny_partner,ambition_partner,shared_interests_partner,interests_correlate,expected_happy_with_sd_people,expected_num_interested_in_me,like,guess_prob_liked,met,match,age_gap,age_gap_abs,same_race,same_race_point
0,0,female,21.0,27.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,35.0,20.0,20.0,20.0,0.0,5.0,6.0,8.0,8.0,8.0,8.0,6.0,...,15.0,15.0,15.0,6.0,9.0,7.0,7.0,6.0,5.0,0.14,3.0,2.0,7.0,6.0,0.0,0,6.0,6.0,-1,-2.0
1,0,female,21.0,22.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,60.0,0.0,0.0,40.0,0.0,0.0,7.0,8.0,10.0,7.0,7.0,5.0,...,15.0,15.0,15.0,7.0,8.0,7.0,8.0,5.0,6.0,0.54,3.0,2.0,7.0,5.0,1.0,0,1.0,1.0,-1,-2.0
2,1,female,21.0,22.0,Asian/PacificIslander/Asian-American,Asian/PacificIslander/Asian-American,2.0,4.0,19.0,18.0,19.0,18.0,14.0,12.0,10.0,10.0,10.0,10.0,10.0,10.0,...,15.0,15.0,15.0,5.0,8.0,9.0,8.0,5.0,7.0,0.16,3.0,2.0,7.0,-99.0,1.0,1,1.0,1.0,1,2.0
3,0,female,21.0,23.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,30.0,5.0,15.0,40.0,5.0,5.0,7.0,8.0,9.0,8.0,9.0,8.0,...,15.0,15.0,15.0,7.0,6.0,8.0,7.0,6.0,8.0,0.61,3.0,2.0,7.0,6.0,0.0,1,2.0,2.0,-1,-2.0
4,0,female,21.0,24.0,Asian/PacificIslander/Asian-American,Latino/HispanicAmerican,2.0,4.0,30.0,10.0,20.0,10.0,10.0,20.0,8.0,7.0,9.0,6.0,9.0,7.0,...,15.0,15.0,15.0,5.0,6.0,7.0,7.0,6.0,6.0,0.21,3.0,2.0,6.0,6.0,0.0,1,3.0,3.0,-1,-2.0

#### 평가 / 중요도

In [49]:
def rating(data, importance, score):
    if data[importance] == -99:
        return -99
    elif data[score] == -99:
        return -99
    else:
        return data[importance] * data[score]

In [50]:
partner_imp = data.columns[8:14] # 상대방의 중요도
partner_rate_me = data.columns[14:20] # 본인에 대한 상대방의 평가
my_imp = data.columns[20:26]
my_rate_partner = data.columns[26:32]

In [51]:
#상대방 관련 새 변수 이름을 저장하는 리스트
new_label_partner = ['attractive_p', 'sincere_p', 'intelligence_p',\
                    'funny_p','ambition_p','shared_interests_p']

#본인 관련 새 변수 이름을 저장하는 리스트
new_label_me = ['attractive_m', 'sincere_m', 'intelligence_m',\
                    'funny_m','ambition_m','shared_interests_m']

In [52]:
for i,j,k in zip(new_label_partner, partner_imp, partner_rate_me):
    data[i] = data.apply(lambda x: rating(x, j, k), axis = 1)

In [53]:
for i,j,k in zip(new_label_me, my_imp, my_rate_partner):
    data[i] = data.apply(lambda x: rating(x, j, k), axis = 1)
#rating 함수 적용(본인이 파트너를 평가했을 때,)

In [54]:
data = pd.get_dummies(data, columns=['gender','race','race_o'], drop_first=True)

In [55]:
data.head()

,has_null,age,age_o,importance_same_race,importance_same_religion,pref_o_attractive,pref_o_sincere,pref_o_intelligence,pref_o_funny,pref_o_ambitious,pref_o_shared_interests,attractive_o,sincere_o,intelligence_o,funny_o,ambitous_o,shared_interests_o,attractive_important,sincere_important,intellicence_important,...,intelligence_p,funny_p,ambition_p,shared_interests_p,attractive_m,sincere_m,intelligence_m,funny_m,ambition_m,shared_interests_m,gender_male,race_Asian/PacificIslander/Asian-American,race_Black/AfricanAmerican,race_European/Caucasian-American,race_Latino/HispanicAmerican,race_Other,race_o_Black/AfricanAmerican,race_o_European/Caucasian-American,race_o_Latino/HispanicAmerican,race_o_Other
0,0,21.0,27.0,2.0,4.0,35.0,20.0,20.0,20.0,0.0,5.0,6.0,8.0,8.0,8.0,8.0,6.0,15.0,20.0,20.0,...,160.0,160.0,0.0,30.0,90.0,180.0,140.0,105.0,90.0,75.0,False,True,False,False,False,False,False,True,False,False
1,0,21.0,22.0,2.0,4.0,60.0,0.0,0.0,40.0,0.0,0.0,7.0,8.0,10.0,7.0,7.0,5.0,15.0,20.0,20.0,...,0.0,280.0,0.0,0.0,105.0,160.0,140.0,120.0,75.0,90.0,False,True,False,False,False,False,False,True,False,False
2,1,21.0,22.0,2.0,4.0,19.0,18.0,19.0,18.0,14.0,12.0,10.0,10.0,10.0,10.0,10.0,10.0,15.0,20.0,20.0,...,190.0,180.0,140.0,120.0,75.0,160.0,180.0,120.0,75.0,105.0,False,True,False,False,False,False,False,False,False,False
3,0,21.0,23.0,2.0,4.0,30.0,5.0,15.0,40.0,5.0,5.0,7.0,8.0,9.0,8.0,9.0,8.0,15.0,20.0,20.0,...,135.0,320.0,45.0,40.0,105.0,120.0,160.0,105.0,90.0,120.0,False,True,False,False,False,False,False,True,False,False
4,0,21.0,24.0,2.0,4.0,30.0,10.0,20.0,10.0,10.0,20.0,8.0,7.0,9.0,6.0,9.0,7.0,15.0,20.0,20.0,...,180.0,60.0,90.0,140.0,75.0,120.0,140.0,105.0,90.0,90.0,False,True,False,False,False,False,False,False,True,False

## 모델링 & 평가

In [56]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data.drop('match', axis=1),
                                                    data['match'],test_size=0.2,
                                                    random_state=100)

In [59]:
import xgboost as xgb

In [60]:
model = xgb.XGBClassifier(n_estimators=500, max_depth=5,random_state=100)

In [62]:
model.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=500, n_jobs=None,
              num_parallel_tree=None, random_state=100, ...)

In [63]:
pred = model.predict(X_test)
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
accuracy_score(y_test, pred)

0.8548736462093863

In [64]:
print(confusion_matrix(y_test,pred))

[[1089   58]
 [ 143   95]]

In [66]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.88      0.95      0.92      1147
           1       0.62      0.40      0.49       238

    accuracy                           0.85      1385
   macro avg       0.75      0.67      0.70      1385
weighted avg       0.84      0.85      0.84      1385

In [67]:
from sklearn.model_selection import GridSearchCV

In [68]:
parameters = {'learning_rate':[0.01,0.1,0.3],
              'max_depth':[5,7,10],
              'subsample':[0.5,0.7,1],
              "n_estimators":[300,500,1000]}

In [69]:
model = xgb.XGBClassifier()

In [70]:
gs_model = GridSearchCV(model,parameters,n_jobs=-1,scoring='f1',cv=5)

In [71]:
gs_model.fit(X_train,y_train)

GridSearchCV(cv=5,
             estimator=XGBClassifier(base_score=None, booster=None,
                                     callbacks=None, colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None, device=None,
                                     early_stopping_rounds=None,
                                     enable_categorical=False, eval_metric=None,
                                     feature_types=None, gamma=None,
                                     grow_policy=None, importance_type=None,
                                     interaction_constraints=None,
                                     learning_rate=None,...
                                     max_cat_to_onehot=None,
                                     max_delta_step=None, max_depth=None,
                                     max_leaves=None, min_child_weight=None,
                                     missing=nan, monotone_constraints=None,
                                     multi_strategy=None, n_estimators=None,
                                     n_jobs=None, num_parallel_tree=None,
                                     random_state=None, ...),
             n_jobs=-1,
             param_grid={'learning_rate': [0.01, 0.1, 0.3],
                         'max_depth': [5, 7, 10],
                         'n_estimators': [300, 500, 1000],
                         'subsample': [0.5, 0.7, 1]},
             scoring='f1')

In [72]:
gs_model.best_params_

{'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 1000, 'subsample': 0.7}

In [74]:
pred = gs_model.predict(X_test)

In [76]:
accuracy_score(y_test,pred)

0.851985559566787

In [77]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.88      0.95      0.91      1147
           1       0.61      0.39      0.47       238

    accuracy                           0.85      1385
   macro avg       0.75      0.67      0.69      1385
weighted avg       0.83      0.85      0.84      1385